<br class="mtop25" />
<div class="info_line top">
	<h3 class="fleft title mbottom0">
		<img alt="" src="cms/admin/images/quiz.png">
		<?php echo $this->_('Statistics');?>				
	</h3>
	<div class="clear"></div>
</div>

<table class="display statistics" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td><?php echo $this->_('Total users');?></td>
			<td width="100" class="right" id="user/total"><img src="cms/admin/images/ajax-loader.gif" alt="" /></td>
		</tr>
		<tr>
			<td><?php echo $this->_('Total pins');?></td>
			<td class="right" id="pin/total"><img src="cms/admin/images/ajax-loader.gif" alt="" /></td>
		</tr>
		<tr>
			<td><?php echo $this->_('Total Wishlists');?></td>
			<td class="right" id="wishlist/total"><img src="cms/admin/images/ajax-loader.gif" alt="" /></td>
		</tr>
		<tr>
			<td><?php echo $this->_('Total Waiting for invitation');?></td>
			<td class="right" id="invite/total"><img src="cms/admin/images/ajax-loader.gif" alt="" /></td>
		</tr>
		<tr>
			<td><?php echo $this->_('Total Orders');?></td>
			<td class="right" id="cart/total"><img src="cms/admin/images/ajax-loader.gif" alt="" /></td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
$(document).ready(function(){
	$('table.statistics td[id]').each(function(i, item){
		selector = $(item).attr('id');
		$.get(new String('<?php echo $this->url(array('module'=>'{MODULE}'),'admin_module',false,false);?>').replace('{MODULE}',selector), function(data){
			$(item).html(data.total);
		}, 'json');
	});
});
</script>