<link href="cms/admin/assets/login.css" rel="stylesheet" type="text/css" />

<div id="content">
  <div class="box mtop25">
    <div class="heading">
      <h1><img src="cms/images/error.png" alt="" /> <?php echo $this->_('Permission Denied!');?></h1>
    </div>
    <div class="content">
      <div style="border: 1px solid #DDDDDD; background: #F7F7F7; text-align: center; padding: 15px;"><?php echo $this->_('You do not have permission to access this page, please refer to your system administrator.');?></div>
    </div>
  </div>
</div>