<?php $module = $this->getRequest()->getModule();?>
<ul>
	<?php if($this->group == 'AdminMenu') { ?>
	<li id="menu_index"<?php if($module == 'admin') {?> class="active"<?php } ?>>
		<a href="<?php echo $this->url(array(),'admin');?>"><?php echo $this->_('Dashboard');?></a>
	</li>
	<?php } ?>
	<?php if($menu) { ?>
	<?php foreach($menu AS $m) { 
		if($m->disabled())
			continue;
	?>
	<li id="menu_<?php echo $m->id;?>"<?php if($module == $m->widget) {?> class="active"<?php } ?>>
		<?php $wroute = (array)unserialize($m->route);?>
		<?php if($m->widget) { ?>
		<?php 
			$route = 'admin_module';
			if(!isset($wroute['module'])) {
				$wroute['module'] = $m->widget;
			} else {
				$route = $m->widget;
			}
		?>
		<a href="<?php echo $this->url($wroute,$route);?>"><?php echo $this->_($m->title);?></a>
		<?php } else { ?>
		<a href="javascript:;"><?php echo $this->_($m->title);?></a>
		<?php } ?>
		<?php echo $this->widget('admin.widget.menu', array('parent_id' => $m->id));?>
	</li>
	<?php } ?>
	<?php } ?>
</ul>