<?php
$me = \User\User::getUserData();
?>

<?php echo $this->getController('home/layout/header_part'); ?>
<!-- WRAPPER - FOOTER HEIGHT // START -->
<div class="container container-padding-header container-padding-footer">
	<!-- CONTENT // START -->
	<?php
	echo $this->widget('user.widget.dashboardmenu', array());
	?>
	<!-- CONTENT // END -->
	<div class="container container-padding-tb-6 container-padding-lr-5 responsive-content">
		<div class="container container-size-1">
			<?php
			echo $this->widget('cart.widget.mysubscriptions', array());
			?>
		</div>
	</div>
</div>
<?php echo $this->getController('home/layout/footer_part'); ?>