<?php echo $this->getController('admin/layout/header_part'); ?>

<?php 
$self = $this;
$recordTable = new \Page\Page();
$recordDescriptionTable = new \Page\PageDescription();
$category = $recordTable->fetchRow($recordTable->makeWhere(array('id' => $this->getRequest()->getRequest('id'))));
$description = $recordDescriptionTable->fetchDescription($recordDescriptionTable->makeWhere(array('page_id' => $this->getRequest()->getRequest('id'))));
if(!$category || !$category->key)
	$this->redirect($this->url([]));



if($category->key == 'pinit') {
	$cols_description = array(
			array(
					'name' => 'title',
					'label' => $this->_('Title'),
					'type' => 'Text',
					'required' => true
			),
			array(
					'name' => 'description',
					'label' => $this->_('Description'),
					'type' => 'Elrte',
					'required' => false
			),
			array(
					'name' => 'pinit_button',
					'label' => '&nbsp;',
					'type' => 'Help',
					'value' => $this->_('To display the pinit button on page write: ${pinit_button}')
			),
			array(
					'name' => 'meta_title',
					'label' => $this->_('Meta Title'),
					'type' => 'Text',
					'required' => false
			),
			array(
					'name' => 'meta_description',
					'label' => $this->_('Meta Description'),
					'type' => 'Textarea',
					'required' => false
			),
			array(
					'name' => 'meta_keywords',
					'label' => $this->_('Meta Keywords'),
					'type' => 'Textarea',
					'required' => false
			),
	);
} else {
	$cols_description = array(
			array(
					'name' => 'title',
					'label' => $this->_('Title'),
					'type' => 'Text',
					'required' => true
			),
			array(
					'name' => 'description',
					'label' => $this->_('Description'),
					'type' => 'Elrte',
					'required' => false
			),
			array(
					'name' => 'meta_title',
					'label' => $this->_('Meta Title'),
					'type' => 'Text',
					'required' => false
			),
			array(
					'name' => 'meta_description',
					'label' => $this->_('Meta Description'),
					'type' => 'Textarea',
					'required' => false
			),
			array(
					'name' => 'meta_keywords',
					'label' => $this->_('Meta Keywords'),
					'type' => 'Textarea',
					'required' => false
			),
	);
}

echo $this->widget('widget.form.phparray', array(
	'head' => array(
		'title' => $this->_('System pages'),
	),
	'descriptionValue' => $description,
	'description' => $cols_description,
	'onSave' => function($values, $widget) use($self, $category, $recordDescriptionTable) {
		if(!$category) {
			$widget->errors = $self->_('Page not found');
			return false;
		}
		
		$recordDescriptionTable->getAdapter()->beginTransaction();
		try {
			$category->save();
			$recordDescriptionTable->insertDescription(array('page_id' => $category->id), $values);
			$recordDescriptionTable->getAdapter()->commit();
			return true;
		} catch (\Core\Exception $e) {
			$recordDescriptionTable->getAdapter()->rollBack();
			$widget->errors = $e->getMessage();
		}
		return false;
	}
));

?>

<?php echo $this->getController('admin/layout/footer_part'); ?>