<?php echo $this->getController('admin/layout/header_part'); ?>

<?php 
$self = $this;
$recordTable = new \Paymentgateway\OrderStatus();
$recordDescriptionTable = new \Paymentgateway\OrderStatusDescription();
$category = $recordTable->fetchRow($recordTable->makeWhere(array('id' => $this->getRequest()->getRequest('id'))));
$description = $recordDescriptionTable->fetchDescription($recordDescriptionTable->makeWhere(array('order_status_id' => $this->getRequest()->getRequest('id'))));
echo $this->widget('widget.form.phparray', array(
	'head' => array(
		'title' => $this->_('Manage Order statuses'),
	),
	'columns' => array(
	),
	'descriptionValue' => $description,
	'description' => array(
		array(
			'name' => 'title',
			'label' => $this->_('Title'),
			'type' => 'Text',
			'required' => true
		),
	),
	'onSave' => function($values, $widget) use($self) {
		$recordTable = new \Paymentgateway\OrderStatus();
		$recordDescriptionTable = new \Paymentgateway\OrderStatusDescription();
		$category = $recordTable->fetchRow($recordTable->makeWhere(array('id' => $self->getRequest()->getRequest('id'))));
		if(!$category) {
			$category = $recordTable->fetchNew();
		}
		
		$recordTable->getAdapter()->beginTransaction();
		try {
			$category->save();
			$recordDescriptionTable->insertDescription(array('order_status_id' => $category->id), $values);
			$recordTable->getAdapter()->commit();
			return true;
		} catch (\Core\Exception $e) {
			$recordTable->getAdapter()->rollBack();
			$widget->errors = $e->getMessage();
		}
		return false;
	}
));

?>

<?php echo $this->getController('admin/layout/footer_part'); ?>