<?php echo $this->getController('home/layout/header_part') ?>

<!-- WRAPPER - FOOTER HEIGHT // START -->
<div class="container container-padding-header container-padding-footer">

<!-- CONTENT // START -->
<div class="container container-padding-tb-6 container-padding-lr-5 responsive-content">
	<div class="container container-size-1 responsive-about">
		<div class="container container-padding-5 container-radius-1 container-shadow-1 bg-color-1">
			<?php $this->render($this->checkSystemView('ajax'), ['languages' => $languages]); ?>
		</div>
	</div>
</div>
<!-- CONTENT // END -->

</div>
<!-- WRAPPER - FOOTER HEIGHT // END -->

<?php echo $this->getController('home/layout/footer_part') ?>